# Generated by Django 2.2.26 on 2022-02-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
